/** Offline, reproducible Sibiu-city pilot. Fit 2025; reserve 2026 for evaluation. */
import { readFile, writeFile } from 'node:fs/promises';
import { calibratedMean } from '../../../app/src/model/marks.js';
import { readSheetRows } from './xlsx.js';
import { readEvnatWorkbook } from './dataset.js';
import { countsTowardCalibration } from './calibrate.js';

const fixture = (name: string): URL => new URL(`../../fixtures/sibiu/${name}`, import.meta.url);

interface School { code: string; name: string }
interface Row { code: string; school: number; romana: number; matematica: number; media: number }
export async function readSibiuRows(year: number): Promise<Row[]> {
  const csv = await readFile(fixture(`evnat-${year}.csv`), 'utf8');
  return csv.trim().split('\n').slice(1).map(line => {
    const cells = line.split(',');
    return { code: cells[0] ?? '', school: Number(cells[1]), romana: Number(cells[2]),
      matematica: Number(cells[3]), media: Number(cells[4]) };
  });
}

export async function fitSibiu() {
  const schools = JSON.parse(await readFile(fixture('schools.json'), 'utf8')) as School[];
  const rows = await readSibiuRows(2025);
  return schools.map(school => {
    const cohort = rows.filter(row => row.code === school.code);
    const n = cohort.length;
    // Thirty national-prior pseudo-observations damp noisy small-school effects.
    const offset = (subject: 'romana' | 'matematica') => n < 20 ? 0 :
      cohort.reduce((sum, row) => sum + row[subject] - calibratedMean(subject, row.school), 0) / (n + 30);
    return { ...school, n, romana: offset('romana'), matematica: offset('matematica') };
  }).sort((a, b) => a.code.localeCompare(b.code));
}

// Explicit maintenance command; never downloads or runs during tests.
if (process.argv.includes('--extract')) {
  const path = process.argv[process.argv.indexOf('--extract') + 1];
  if (!path) throw new Error('--extract requires the official 2024–2025 directory workbook');
  const schools: School[] = [];
  let header: string[] | undefined;
  for await (const row of readSheetRows(path)) {
    if (row.includes('Cod SIIIR unitate')) { header = row; continue; }
    if (!header) continue;
    const columns = header;
    const cell = (name: string): string => {
      const i = columns.indexOf(name);
      if (i < 0) throw new Error(`School directory missing column ${name}`);
      return row[i] ?? '';
    };
    if (cell('Judet PJ') === 'SB' && cell('Localitate unitate') === 'SIBIU') {
      schools.push({ code: cell('Cod SIIIR unitate'),
        name: cell('Denumire lunga unitate').replaceAll('Ş', 'Ș').replaceAll('Ţ', 'Ț').normalize('NFC') });
    }
  }
  if (schools.length === 0) throw new Error('No Sibiu city schools in directory');
  const codes = new Set(schools.map(school => school.code));
  const observed = new Set<string>();
  for (const year of [2025, 2026]) {
    const rows: string[] = [];
    for await (const row of readEvnatWorkbook(new URL(`../../raw/evnat/evnat-${year}.xlsx`, import.meta.url).pathname)) {
      if (row.schoolCode && codes.has(row.schoolCode) && countsTowardCalibration(row)) {
        rows.push([row.schoolCode, row.schoolMedia, row.romana, row.matematica, row.media].join(','));
        observed.add(row.schoolCode);
      }
    }
    if (rows.length === 0) throw new Error(`No eligible Sibiu candidates in ${year}`);
    await writeFile(fixture(`evnat-${year}.csv`),
      'school_code,school_media,romana,matematica,media\n' + rows.sort().join('\n') + '\n');
  }
  await writeFile(fixture('schools.json'), JSON.stringify(schools.filter(school => observed.has(school.code)), null, 2) + '\n');
}

if (process.argv.includes('--emit')) {
  const schools = await fitSibiu();
  await writeFile('app/src/model/sibiu-schools.ts',
    '// Generated by node --import tsx pipeline/src/evnat/sibiu.ts --emit.\n' +
    '// Official 2025 results, Sibiu city only; see docs/SIBIU.md.\n' +
    `export const SIBIU_SCHOOLS = ${JSON.stringify(schools, null, 2)} as const;\n`);
}
